name: SkillsMC
version: ${project.version}
main: ragnaorok.Main.Main
api-version: 1.17
authors: [ Ragnaorok ]
description: 1.17 Spigot Plugin
commands:
  skill:
    description: select a skill!
    usage: /<command>
  souls:
    description: a currency command
  saveAll:
    description: a save command
    usage: saveAll
  kaboom:
    description: blow up
    usage: kaboom
  reinforce:
    description: enchants shields
    usage: reinforce
  check:
    description: check enchants
    usage: checks enchants
