name: KillCounter
version: ${project.version}
main: ragnaorok.Main.Main
api-version: 1.16
authors: [ Ragnaorok ]
description: 1.16.5 Spigot Plugin
commands:
  flame:
    description: create a flame!
    usage: /<command>